
# 推荐 clippy 配置说明：
# 1. 建议用命令行参数启用严格检查：
#    cargo clippy -- -W clippy::all -W clippy::pedantic -W clippy::nursery -W clippy::cargo
# 2. .clippy.toml 仅用于高级定制（如 msrv、阈值、特殊规则）。

# 示例：最低支持 Rust 版本
msrv = "1.70"


# 允许某些 crate 出现多个版本而不触发 clippy::multiple_crate_versions
allowed-duplicate-crates = [
  "windows-sys",
  "windows-link",
  "thiserror",
  "thiserror-impl",
  "getrandom",
  "hashbrown",
  "syn",
  "wasi",
  "ahash",
  "toml_datetime",
  "toml_edit",
  "winnow",
]

# 可选：对部分规则进行强制
# deny = [
#     "clippy::unwrap_used",             # 禁止使用 unwrap
#     "clippy::expect_used",             # 禁止使用 expect
# ]
