# 配置 rustfmt 的格式化规则
# 参考：https://rust-lang.github.io/rustfmt/

# 使用 2018 版本的格式化规则
edition = "2021"

# 最大行宽
max_width = 100

# 在控制流结构中强制使用花括号
force_multiline_blocks = true

# 对注释进行规范化
normalize_comments = true

# 对 doc 注释进行规范化
normalize_doc_attributes = true

# 对引用进行规范化
reorder_imports = true

# 使用 Unix 风格的行尾
newline_style = "Unix"
