[package]
name = "sqllog-analysis"
version = "1.0.0"
edition = "2024"
authors = ["guangl"]
description = "达梦数据库的 sqllog 日志分析工具"
license = "MIT"
repository = "https://github.com/guangl/sqllog-analysis"
keywords = ["database", "log", "analysis", "dm", "rust"]
categories = [
  "command-line-utilities",
  "development-tools::debugging",
  "data-processing",
]

[dependencies]
anyhow = "1.0.100"
regex = "1.11"
lazy_static = "1.5"
tempfile = "3.22"
thiserror = "2.0"
log = "0.4"
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["fmt", "env-filter"] }
tracing-appender = "0.2"
tracing-log = "0.2"
chrono = "0.4"
duckdb = { version = "1.4.0", features = ["bundled"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
toml = "0.7"
dirs = "4"

[dev-dependencies]
criterion = "0.7"

[[bench]]
name = "datetime_bench"
harness = false

[[bench]]
name = "core_functions_bench"
harness = false
