[package]
name = "sqllog-analysis"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.99"
dialoguer = { version = "0.12.0", features = ["fuzzy-select"] }
duckdb = "1.4.0"

[dev-dependencies]
criterion = "0.5"
regex = "1.10"
lazy_static = "1.4"
chrono = "0.4"

[[bench]]
name = "datetime_benchmark"
harness = false
