[package]
name = "sqllog-analysis"
version = "0.1.0"
edition = "2024"
authors = ["guangl"]
description = "达梦数据库的 sqllog 日志分析工具"
license = "MIT"
repository = "https://github.com/guangl/sqllog-analysis"

[dependencies]
anyhow = "1.0.99"
dialoguer = { version = "0.12.0", features = ["fuzzy-select"] }
regex = "1.10"
lazy_static = "1.4"
tempfile = "3.8"
memchr = "2.6"

thiserror = "1.0"

[dev-dependencies]
criterion = "0.5"
regex = "1.10"
lazy_static = "1.4"
chrono = "0.4"

[[bench]]
name = "datetime_benchmark"
harness = false

[[bench]]
name = "sqllog_benchmark"
harness = false
