[package]
name = "sqllog-analysis"
version = "1.0.0"
edition = "2021"
authors = ["guangl"]
description = "达梦数据库的 sqllog 日志解析和分析工具库"
license = "MIT"
repository = "https://github.com/guangl/sqllog-analysis"
keywords = ["database", "log", "analysis", "dm", "rust"]
categories = [
  "command-line-utilities",
  "development-tools::debugging",
  "data-processing",
]

[lib]
name = "sqllog_analysis"
path = "src/lib.rs"

[[bin]]
name = "sqllog-cli"
path = "src/main.rs"

[dependencies]
# 核心依赖
regex = "1.11"
lazy_static = "1.5"
thiserror = "2.0"
serde = { version = "1.0", features = ["derive"] }

# 日志依赖
log = "0.4"
