[log]
enable_stdout = true
log_dir = "logs"
level = "info"

[database]
db_path = "sqllogs.duckdb"
use_in_memory = false
overwrite_db = false

[export]
enabled = true
format = "csv"
out_path = "sqllogs.csv"
per_thread_out = false
overwrite_or_ignore = false
overwrite = false
append = false
# file_size_bytes = 104857600

[sqllog]
sqllog_dir = "sqllog"
chunk_size = 1000
# 解析器线程数量（默认：10）
parser_threads = 10
# 是否写入解析错误到文件
write_errors = true
# 错误输出文件路径
errors_out_path = "parse_errors.jsonl"
