[log]
enable_stdout = true
log_dir = "logs"
level = "trace"

[sqllog]
sqllog_dir = "sqllog"
chunk_size = 10000
write_errors = true
thread_count = 2
batch_size = 500
queue_buffer_size = 2000
errors_out_path = "parse_errors.jsonl"
