name: Rust Tests

on:
  push:
    branches: ["main"] # 在推送到主分支时触发
  pull_request:
    branches: ["main"] # 在创建针对主分支的PR时触发

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable

      - name: Cache dependencies
        uses: Swatinem/rust-cache@v2

      - name: Install clippy
        run: rustup component add clippy

      - name: Run clippy (strict)
        run: |
          # Treat clippy warnings as errors and enable pedantic/nursery lints
          cargo clippy --all-features -- -D warnings -W clippy::pedantic -W clippy::nursery -W clippy::cargo

      - name: Run tests
        run: cargo test --all-features
